// ── Display data (preserved from original planetData) ────────────────────────
export const planetData = {
  sun: {
    name: "SUN",
    symbol: "\u2609",
    subtitle: "Yellow Dwarf Star",
    info: "The heart of our solar system",
    distance: "0",
    diameter: "1,392,000 km",
    period: "\u2014",
    dayLength: "25 Earth days",
    temperature: "5,500\u00b0C (surface)",
    gravity: "28g",
    moons: 0,
    atmosphere: "Hydrogen, Helium",
    facts: [
      "Contains 99.8% of system's mass",
      "Powers all life on Earth",
      "Nuclear fusion reactor at core"
    ]
  },
  "asteroid-belt": {
    name: "ASTEROID BELT",
    symbol: "\u2604",
    subtitle: "Main Belt Region",
    info: "Rocky debris field between Mars and Jupiter",
    distance: "329-478 million km",
    diameter: "~150 million km wide",
    period: "3-6 Earth years (varies)",
    dayLength: "N/A",
    temperature: "-73\u00b0C to -108\u00b0C",
    gravity: "Near zero (individual asteroids)",
    moons: 0,
    atmosphere: "None",
    facts: [
      "Formed from failed planet formation",
      "Jupiter's gravity prevented coalescence",
      "Ceres contains 25% of belt's total mass",
      "Safe for spacecraft (sparse distribution)",
      "Total mass: ~3% of Moon's mass",
      "Over 1.3 million cataloged asteroids"
    ]
  },
  mercury: {
    name: "MERCURY",
    symbol: "\u263f",
    subtitle: "The Swift Planet",
    info: "Smallest planet in solar system",
    distance: "57.9 million km",
    diameter: "4,879 km",
    period: "88 Earth days",
    dayLength: "59 Earth days",
    temperature: "-173\u00b0C to 427\u00b0C",
    gravity: "0.38g",
    moons: 0,
    atmosphere: "None",
    facts: [
      "Fastest orbit around Sun",
      "Extreme temperature swings",
      "Named after Roman messenger god"
    ]
  },
  venus: {
    name: "VENUS",
    symbol: "\u2640",
    subtitle: "Earth's Evil Twin",
    info: "Hottest planet in solar system",
    distance: "108.2 million km",
    diameter: "12,104 km",
    period: "225 Earth days",
    dayLength: "243 Earth days (retrograde)",
    temperature: "462\u00b0C (average)",
    gravity: "0.90g",
    moons: 0,
    atmosphere: "CO\u2082, Sulfuric Acid clouds",
    facts: [
      "Rotates backwards (retrograde)",
      "Day longer than year",
      "Volcanic hellscape"
    ]
  },
  earth: {
    name: "EARTH",
    symbol: "\ud83d\udea8",
    subtitle: "The Blue Planet",
    info: "Our home in the cosmos",
    distance: "149.6 million km",
    diameter: "12,742 km",
    period: "365.25 days",
    dayLength: "24 hours",
    temperature: "-88\u00b0C to 58\u00b0C",
    gravity: "1.0g",
    moons: 1,
    atmosphere: "N\u2082, O\u2082",
    facts: [
      "Only known planet with life",
      "71% covered by water",
      "Perfect conditions for civilization"
    ]
  },
  mars: {
    name: "MARS",
    symbol: "\u2642",
    subtitle: "The Red Planet",
    info: "Future human colony",
    distance: "227.9 million km",
    diameter: "6,779 km",
    period: "687 Earth days",
    dayLength: "24.6 hours",
    temperature: "-140\u00b0C to 20\u00b0C",
    gravity: "0.38g",
    moons: 2,
    atmosphere: "CO\u2082 (thin)",
    facts: [
      "Home to Olympus Mons (tallest mountain)",
      "Ancient riverbeds discovered",
      "Target for human colonization"
    ]
  },
  jupiter: {
    name: "JUPITER",
    symbol: "\u2643",
    subtitle: "King of Planets",
    info: "Largest planet in solar system",
    distance: "778.5 million km",
    diameter: "139,820 km",
    period: "11.9 Earth years (4,333 days)",
    dayLength: "10 hours",
    temperature: "-145\u00b0C (cloud tops)",
    gravity: "2.5g",
    moons: 79,
    atmosphere: "H\u2082, He",
    facts: [
      "Great Red Spot storm (300+ years old)",
      "Protects Earth from asteroids",
      "Could contain 1,300 Earths"
    ]
  },
  saturn: {
    name: "SATURN",
    symbol: "\u2644",
    subtitle: "Lord of the Rings",
    info: "Most spectacular ring system",
    distance: "1.4 billion km",
    diameter: "116,460 km",
    period: "29.5 Earth years (10,759 days)",
    dayLength: "10.7 hours",
    temperature: "-178\u00b0C",
    gravity: "1.1g",
    moons: 82,
    atmosphere: "H\u2082, He",
    facts: [
      "Rings made of ice and rock",
      "Low density (would float on water)",
      "Hexagonal storm at north pole"
    ]
  },
  uranus: {
    name: "URANUS",
    symbol: "\u2645",
    subtitle: "The Sideways Planet",
    info: "Ice giant with extreme tilt",
    distance: "2.9 billion km",
    diameter: "50,724 km",
    period: "84 Earth years (30,687 days)",
    dayLength: "17.2 hours (retrograde)",
    temperature: "-224\u00b0C",
    gravity: "0.89g",
    moons: 27,
    atmosphere: "H\u2082, He, CH\u2084",
    facts: [
      "Rotates on its side (98\u00b0 tilt)",
      "Faint ring system",
      "Methane gives blue-green color"
    ]
  },
  neptune: {
    name: "NEPTUNE",
    symbol: "\u2646",
    subtitle: "The Windy World",
    info: "Fastest winds in solar system",
    distance: "4.5 billion km",
    diameter: "49,244 km",
    period: "165 Earth years (60,190 days)",
    dayLength: "16 hours",
    temperature: "-214\u00b0C",
    gravity: "1.1g",
    moons: 14,
    atmosphere: "H\u2082, He, CH\u2084",
    facts: [
      "Winds reach 2,100 km/h",
      "Dark Spot storms",
      "Discovered by mathematics"
    ]
  },
  pluto: {
    name: "PLUTO",
    symbol: "\u2647",
    subtitle: "The Heart of Ice",
    info: "Dwarf planet in Kuiper Belt",
    distance: "5.9 billion km",
    diameter: "2,377 km",
    period: "248 Earth years (90,560 days)",
    dayLength: "6.4 Earth days",
    temperature: "-229\u00b0C",
    gravity: "0.06g",
    moons: 5,
    atmosphere: "N\u2082, CH\u2084 (seasonal)",
    facts: [
      "Heart-shaped ice plain (Tombaugh Regio)",
      "Reclassified as dwarf planet (2006)",
      "Five moons in complex dance"
    ]
  }
}

// ── Physics configuration ────────────────────────────────────────────────────
// Coordinate system: Sun at (0,0), distances in pixels
// G and masses tuned for visual stability at 1200x1200 space

export const G = 100

// Start angles derived from CSS animation-delay / duration * 2PI
// e.g. Mercury: delay=-1s, duration=6s → 1/6 * 2PI ≈ 1.047 rad
export const bodyConfig = [
  // ── Sun ──
  {
    id: 'sun',
    mass: 10000,
    radius: 40,
    orbitRadius: 0,
    parent: null,
    domSelector: '.sun',
    color: '#ffcc00',
    trailMax: 0,
    startAngle: 0,
  },
  // ── Planets ──
  {
    id: 'mercury',
    mass: 0.01,
    radius: 6,
    orbitRadius: 70,
    parent: 'sun',
    domSelector: '.mercury',
    color: '#a5a5a5',
    trailMax: 400,
    startAngle: (1 / 6) * Math.PI * 2,       // delay -1s / 6s
  },
  {
    id: 'venus',
    mass: 0.05,
    radius: 11,
    orbitRadius: 105,
    parent: 'sun',
    domSelector: '.venus',
    color: '#e3bb76',
    trailMax: 500,
    startAngle: (4 / 6.1) * Math.PI * 2,     // delay -4s / 6.1s
  },
  {
    id: 'earth',
    mass: 5,
    radius: 12.5,
    orbitRadius: 150,
    parent: 'sun',
    domSelector: '.earth',
    color: '#2b82c9',
    trailMax: 600,
    startAngle: (2 / 10) * Math.PI * 2,      // delay -2s / 10s
  },
  {
    id: 'mars',
    mass: 2,
    radius: 9,
    orbitRadius: 195,
    parent: 'sun',
    domSelector: '.mars',
    color: '#e27b58',
    trailMax: 600,
    startAngle: (5 / 18.8) * Math.PI * 2,
  },
  {
    id: 'jupiter',
    mass: 50,
    radius: 25,
    orbitRadius: 275,
    parent: 'sun',
    domSelector: '.jupiter',
    color: '#d39c7e',
    trailMax: 600,
    startAngle: (10 / 40) * Math.PI * 2,
  },
  {
    id: 'saturn',
    mass: 30,
    radius: 22.5,
    orbitRadius: 350,
    parent: 'sun',
    domSelector: '.saturn',
    color: '#c5ab6e',
    trailMax: 600,
    startAngle: (15 / 60) * Math.PI * 2,
  },
  {
    id: 'uranus',
    mass: 10,
    radius: 15,
    orbitRadius: 425,
    parent: 'sun',
    domSelector: '.uranus',
    color: '#b3d1d1',
    trailMax: 600,
    startAngle: (20 / 80) * Math.PI * 2,
  },
  {
    id: 'neptune',
    mass: 10,
    radius: 15,
    orbitRadius: 480,
    parent: 'sun',
    domSelector: '.neptune',
    color: '#6081ff',
    trailMax: 600,
    startAngle: (30 / 120) * Math.PI * 2,
  },
  {
    id: 'pluto',
    mass: 0.5,
    radius: 5,
    orbitRadius: 550,
    parent: 'sun',
    domSelector: '.pluto',
    color: '#7f7f7f',
    trailMax: 600,
    startAngle: (40 / 150) * Math.PI * 2,
  },
  // ── Moons ──
  {
    id: 'moon',
    mass: 0.001,
    radius: 3,
    orbitRadius: 22.5,
    parent: 'earth',
    domSelector: '.moon',
    color: '#dddddd',
    trailMax: 200,
    startAngle: (1 / 2.7) * Math.PI * 2,
  },
  {
    id: 'phobos',
    mass: 0.0001,
    radius: 1.5,
    orbitRadius: 15,
    parent: 'mars',
    domSelector: '.phobos',
    color: '#9d8e87',
    trailMax: 150,
    startAngle: (0.5 / 1) * Math.PI * 2,
  },
  {
    id: 'deimos',
    mass: 0.0001,
    radius: 1,
    orbitRadius: 22.5,
    parent: 'mars',
    domSelector: '.deimos',
    color: '#9d8e87',
    trailMax: 150,
    startAngle: (1.5 / 3) * Math.PI * 2,
  },
  {
    id: 'io',
    mass: 0.001,
    radius: 2,
    orbitRadius: 35,
    parent: 'jupiter',
    domSelector: '.io',
    color: '#f9e231',
    trailMax: 150,
    startAngle: (0.5 / 2) * Math.PI * 2,
  },
  {
    id: 'europa',
    mass: 0.001,
    radius: 1.75,
    orbitRadius: 45,
    parent: 'jupiter',
    domSelector: '.europa',
    color: '#fdf5e6',
    trailMax: 150,
    startAngle: (1 / 4) * Math.PI * 2,
  },
  {
    id: 'ganymede',
    mass: 0.002,
    radius: 2.5,
    orbitRadius: 57.5,
    parent: 'jupiter',
    domSelector: '.ganymede',
    color: '#95877c',
    trailMax: 150,
    startAngle: (2 / 7) * Math.PI * 2,
  },
  {
    id: 'titan',
    mass: 0.002,
    radius: 3,
    orbitRadius: 60,
    parent: 'saturn',
    domSelector: '.titan',
    color: '#e3bb76',
    trailMax: 150,
    startAngle: (3 / 10) * Math.PI * 2,
  },
  {
    id: 'titania',
    mass: 0.001,
    radius: 1.5,
    orbitRadius: 25,
    parent: 'uranus',
    domSelector: '.titania',
    color: '#dcdcdc',
    trailMax: 150,
    startAngle: (1 / 5) * Math.PI * 2,
  },
  {
    id: 'triton',
    mass: 0.001,
    radius: 2,
    orbitRadius: 30,
    parent: 'neptune',
    domSelector: '.triton',
    color: '#d2f8f8',
    trailMax: 150,
    startAngle: (1 / 6) * Math.PI * 2,
    retrograde: true,
  },
  {
    id: 'charon',
    mass: 0.001,
    radius: 1,
    orbitRadius: 10,
    parent: 'pluto',
    domSelector: '.charon',
    color: '#a5a5a5',
    trailMax: 100,
    startAngle: (0.5 / 1) * Math.PI * 2,
    retrograde: true,
  },
]
